### ISSUE TITLE
Admin-side support?

### ISSUE THREAD

**Issue by christianparobek** [powerapi/powerapi-ruby#4]
Hi Henri,
Thanks for tackling this project. From what I can gather from your github and website, it seems that `powerapi-ruby` is more for parent/student-side access to PowerSchool servers. Does your project also grant access for teachers/admins? We're interested in accessing our database programmatically to follow trends, identify students who need extra support, etc.
Thanks!

**Comment by henriwatson** [comment]
Hey Christian,

It's great to see folks interested in taking advantage of the detailed data Student Information Systems keep track of in order to help students get on track before it's too late. It was certainly one of my motivations when writing PowerAPI for my own data mining.

Sadly, PowerAPI isn't really meant for use by the school office (in fact, its main goal is to allow students to grab their own data *without* having to get special access from the school office).

Pearson *does* have APIs available for office access and you can find information regarding these by searching [PowerSource](https://powersource.pearsonschoolsystems.com/). I have intentionally stayed away from looking at the documentation available on PowerSource to avoid "tainting" PowerAPI, so I can't really say much else regarding the information available through PowerSource.

PowerSchool's built in data export features might also get you data that's raw enough to do the sort of analysis you're describing, though it'd be difficult to automate that extraction (unless one of the internal APIs supports it).

As far as I know, the only publicly available resource that might help you is the [Pearson-Rest Web Services](http://sales.powerschool.com/pearson-rest/services/listServices) listServices call. You can find WSDLs for the APIs consumed by Pearson's mobile apps, which might get you closer to the data you're looking for. Unfortunately, these don't really detail how authentication works (I had to figure that out on my own for PowerAPI).

Cheers.

**Comment by christianparobek** [comment]
Thanks Henri, this is really helpful! Provides some context for PowerSchool's API that was hard to find otherwise!
